### ISSUE TITLE
Error 401, please improve debugging ...

### ISSUE THREAD

**Issue by adminy** [fossteams/teams-api#2]
![Screenshot 2022-03-03 at 09 25 38](https://user-images.githubusercontent.com/22717869/156535821-2309abf2-9f9b-47c8-bf55-941f64fe36ad.png)

This generic error can be happening anywhere, I'm guessing here where it might happen. Improve error reporting please.

**Comment by denysvitali** [comment]
The error is happening on the CLI, please open an issue there.
