### ISSUE TITLE
Some files couldn't be uploaded because their missing necessary data

### ISSUE THREAD

**Issue by dlanderson290** [fossteams/teams-api#4]
Some System info if needed:
- Linux Mint 21.1 Cinnamon
- Cinnamon Version 5.6.8
- Kernel: 6.2.8-060208-generic
- Processor: 13th Gen Intel© Core™ i9-13900 × 24

I use Syncthing-GTK to backup all my wireless cameras, devices and smart phones for the entire family to an auto-mounted hard drive; file system ext4; at mount point let's say /mnt/share
the /share folder has subfolders for each family member and all their devices.

I'm running **U**nofficial **M**icrosoft **T**eams client for Linux using Electron version 1.1.1 Flatpack.  I'll call it **UMT**

If I attempt to drag and drop a photo, video or data file (*.txt, *.csv, *.pdf, ect) into UMT then I get the error "Some files couldn't be uploaded because their missing necessary data"
File permission from /mnt/share/subfolder(s) are 664.

If I drag and drop a file from /mnt/share/subfolder to the desktop; user=me, then drag and drop the file from the desktop into UMT it will upload.  File permission from /home/me/Desktop are 664 as it was copied.

If I launch micro$OFT Team$ web client, then drag and drop a file from the /mnt/share/subfolder(s) location it will upload.

**Comment by denysvitali** [comment]
Are you sure you've opened a bug to the right project?

What is "Unofficial Microsoft Teams client for Linux"?

**Comment by dlanderson290** [comment]
Sorry, I didn't realize this was a wrapper.  I'll re-post on [teams-for-linux](https://github.com/IsmaelMartinez/teams-for-linux)
